[package]
name = "yolodoro"
version = "0.1.0"
authors = ["Moritz Ulrich <moritz@tarn-vedra.de>"]

[dependencies]
notify-rust = "3.5.0"
quicli = "0.4.0"
structopt = "0.2.14"
ctrlc = { version = "3.1.1", features = ["termination"] }

